"""
    This is a simple program to send OTP to the given email id using python smtplib

    Author: umairkarel
"""
from dotenv import load_dotenv, find_dotenv
from os import environ as env
import random
from re import fullmatch
import smtplib

load_dotenv(find_dotenv())

# Create a file named ".env" in the sample floder where this file is stored and save the keys as below
# EMAIL=your_email
# PASSWORD=email_password (app password)

SENDER_EMAIL = env.get('EMAIL')
SENDER_EMAIL_PASSWD = env.get('PASSWORD')
OTP_LENGTH = 4

# regular expression for validating an Email
regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'



def sendMail(msg, receiver):
    """
    The function to send an e-mail to a specific email address.

    Parameters:
        msg (str): The content or body of the email to be sent
        receiver (str): Email address of the recipient
    """

    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()

    s.login(SENDER_EMAIL, SENDER_EMAIL_PASSWD)
    s.sendmail(SENDER_EMAIL, receiver, msg)
    s.quit()


def generateOTP(length):
    """
    The function to generates a random OTP number.

    Parameters:
        length (int): The length of an OTP to be generated.

    Returns:
        otp (str): A random OTP of given length.
    """

    digits = "0123456789"
    otp = random.sample(digits, length)

    return "".join(otp)


def getInput():
    """
    The function to input valid email address.

    Returns:
        email (str): Given valid input email address
    """

    print("Please Enter your Email to receive OTP")
    email = input("Email: ")

    # While Email is not valid take new input
    while fullmatch(regex, email) == None:
        print("Please enter a valid email address")
        email = input("Email: ")

    return email


def validateOTP(org_otp):
    """
    The function to validate the OTP sent to the user.

    Parameters:
        org_otp (str): The original OTP generated by the program and sent to user.
    """

    print()
    print("OTP is sent to the given email address")
    print()
    print("Please enter the OTP to proceed")
    otp = input("OTP: ")

    if otp.strip() == org_otp:
        print("Given OTP was correct")
    else:
        print("Given OTP was incorrect")


def main():
    receiver = getInput()
    OTP = generateOTP(OTP_LENGTH)

    msg = '\n\nThe One Time Password(OTP) is: ' + str(OTP)

    sendMail(msg, receiver)
    validateOTP(OTP)


if __name__ == '__main__':
    main()
